[2024-05-28T21:15:13.159+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T21:15:13.178+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dag_1.python_task manual__2024-05-28T21:14:35.547091+00:00 [queued]>
[2024-05-28T21:15:13.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dag_1.python_task manual__2024-05-28T21:14:35.547091+00:00 [queued]>
[2024-05-28T21:15:13.187+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-05-28T21:15:13.201+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): python_task> on 2024-05-28 21:14:35.547091+00:00
[2024-05-28T21:15:13.208+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T21:15:13.209+0000] {standard_task_runner.py:63} INFO - Started process 180 to run task
[2024-05-28T21:15:13.210+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_dag_1', 'python_task', 'manual__2024-05-28T21:14:35.547091+00:00', '--job-id', '2512', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp29840coo']
[2024-05-28T21:15:13.213+0000] {standard_task_runner.py:91} INFO - Job 2512: Subtask python_task
[2024-05-28T21:15:13.261+0000] {task_command.py:426} INFO - Running <TaskInstance: example_dag_1.python_task manual__2024-05-28T21:14:35.547091+00:00 [running]> on host 6ecac41592ab
[2024-05-28T21:15:13.365+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gurlenko.13032001@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_dag_1' AIRFLOW_CTX_TASK_ID='python_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T21:14:35.547091+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T21:14:35.547091+00:00'
[2024-05-28T21:15:13.368+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T21:15:13.369+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T21:15:13.370+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag.py", line 20, in get_rate
    ti = T
         ^
NameError: name 'T' is not defined
[2024-05-28T21:15:13.382+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=example_dag_1, task_id=python_task, run_id=manual__2024-05-28T21:14:35.547091+00:00, execution_date=20240528T211435, start_date=20240528T211513, end_date=20240528T211513
[2024-05-28T21:15:13.396+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2512 for task python_task (name 'T' is not defined; 180)
[2024-05-28T21:15:13.432+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T21:15:13.463+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T21:15:13.465+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
